name: Build and publish manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Run script file
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          chmod +x ./images_build_script.sh
          ./images_build_script.sh
        shell: bash
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
      - name: Push app image to DO Container Registry 
        run: docker push registry.digitalocean.com/dc-apps-registry/opensourcepos:latest-app
      - name: Push db image to DO Container Registry 
        run: docker push registry.digitalocean.com/dc-apps-registry/opensourcepos:sqlscript
